name: Get service principal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
      
    - name: Where am I
      run: pwd
      shell: bash
      
    - name: What's inside
      run: ls -a process
      shell: bash
      
    - name: Checkout code action
      uses: actions/checkout@v3
      with:
        repository: notanops/GetServicePrincipal
        clean: false
      
    - name: Where am I
      run: pwd
      shell: bash
    
    - name: What's inside
      run: ls -a process
      shell: bash
    
    - name: Get service principal
      uses: notanops/GetServicePrincipal@main
      with:
        stack-name: 'build'
