name: Get service principal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  GetServicePrincipal:
    name: Get service principal name from Pulumi config
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
       
    - name: Checkout Pulumi project
      uses: actions/checkout@v3 
      
    - uses: suisei-cn/actions-download-file@v1.3.0
      name: Download the file
      with:
        url: "https://github.com/notanops/GetServicePrincipal/blob/main/main.go"
        target: ./
        
    - name: What's inside
      run: ls -a
      shell: bash
        
    - name: Run script
      run: go run main.go
      shell: bash

