name: Get service principal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Checkout code action
      uses: actions/checkout@v3
      with:
        repository: notanops/GetServicePrincipal
    
    - name: Get service principal
      uses: notanops/GetServicePrincipal@main
      with:
        input.stack-name: 'Build'
