name: Get service principal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  GetServicePrincipal:
    name: Get service principal name from Pulumi config
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
       
    - name: Checkout Pulumi project
      uses: actions/checkout@v3 
        
    - name: Download binary
      uses: giantswarm/install-binary-action@v1.1.0
      with:
        download_url: "https://github.com/notanops/GetServicePrincipal/raw/main/app.tar.gz"
    
    - name: Extract binary
      run: tar -xvzf app.tar.gz
      shell: bash
      
    - name: Make it executable
      run: chmod +x getserviceprincipal
      shell: bash
      working-directory: project
      
    - name: Get service principal
      run: ./getserviceprincipal
