name: Get service principal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  GetServicePrincipal:
    name: Get service principal name from Pulumi config
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
       
    - name: Checkout Pulumi project
      uses: actions/checkout@v3 
        
    - uses: actions/checkout@v3
      with:
        repository: notanops/GetServicePrincipal
        
    - name: What's inside
      run: ls -a
      shell: bash
