name: Get service principal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  GetServicePrincipal:
    name: Get service principal name from Pulumi config
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Pulumi project
      uses: actions/checkout@v3 
        
    - name: Get service principal
      uses: notanops/GetServicePrincipal@main
      with:
        stack-name: 'build'
